export const REACT_APP_SUPABASE_URL = "https://zltpicawosxtjfsidwmr.supabase.co";
export const REACT_APP_SUPABASE_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsdHBpY2F3b3N4dGpmc2lkd21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzExNzkxNjUsImV4cCI6MTk4Njc1NTE2NX0.W4YXoi1MQZ8HpZVlBgFb05XzZR9xaZXBpy_ysgVIR6o";
